### ISSUE TITLE
Is k8s with crio supported?

### ISSUE THREAD

**Issue by dudniksergei** [Granulate/gprofiler#293]
Hi!
Is k8s with crio supported? So could I just change socket from /var/run/docker/docker.sock to  /var/run/crio/crio.sock?

**Comment by Jongy** [comment]
Hi :) Support for crio and containerd is planned but not ready yet. The protocol used over `docker.sock` differs from the others, so I don't think it'll just work if you change the path.

As for gProfiler itself - it will run alright on k8s no matter what the container runtime is, you will get profiles just the same, but they will not be correlated with their containers/pods/deployments.

**Comment by Jongy** [comment]
You can use the local output mode as described [here](https://github.com/Granulate/gprofiler#output-options). It will write files locally and you can collect them. The Performance Studio itself is not available on air-gapped environments, sadly.

**Comment by Jongy** [comment]
https://github.com/Granulate/gprofiler/pull/296 will work for crio-o as well :) Will be merged soon.

**Comment by Jongy** [comment]
Hi @dudniksergei, I forgot to update you here. #296 was merged and released in 1.2.15, so you can just grab the latest release and it will have crio-o support out of the box - you don't need to change anything.

Closing this as the original request was fulfilled, feel free to open another issue for other questions.

**Comment by dudniksergei** [comment]
> Hi @dudniksergei, I forgot to update you here. #296 was merged and released in 1.2.15, so you can just grab the latest release and it will have crio-o support out of the box - you don't need to change anything.
> 
> Closing this as the original request was fulfilled, feel free to open another issue for other questions.

thank you!
