### ISSUE TITLE
No module named gprofiler

### ISSUE THREAD

**Issue by geokas7** [Granulate/gprofiler#322]
Hello,

We are running Gprofiler as an executable. We ran the code below.

wget https://github.com/Granulate/gprofiler/releases/latest/download/gprofiler_$(uname -m) -O gprofiler
sudo chmod +x gprofiler
sudo sh -c "setsid ./gprofiler -cu --token <token> --service-name <service> [options] > /dev/null 2>&1 &"
sleep 1
pgrep gprofiler # make sure gprofiler has started

We checked that Gprofiler started (pgrep gprofiler).
We tried to profile a test.py file with the code below:
python3 -m gprofiler -cu -token <token> --service-name <service> python test.py
The result is : 
/usr/bin/python3: No module named gprofiler

Could you provide us a solution to this issue?

Best,
George

**Comment by Jongy** [comment]
Hi @geokas7 !

You don't need to start your profiled script with `python -m gprofiler ... python myscript.py`. Upon being started, gProfiler automatically profiles *all* Python code running on your system. So you can just run `python test.py`, and it will be profiled by gProfiler that was started earlier.

**Comment by Jongy** [comment]
I'm closing this ticket as the question was answered. If you have any additional questions, feel free to open a new one (or reopen this oen with subsequent questions on this topic).
