### ISSUE TITLE
    ModuleNotFoundError: No module named 'configargparse'

### ISSUE THREAD

**Issue by sridharchary** [Granulate/gprofiler#344]
I Trying to run Gprofiler in my local but it's gives an error 
like  import configargparse    ModuleNotFoundError: No module named 'configargparse'
after install ConfigArgParse==1.3 from file of requirements.txt. I check with my python mode to import I got import successfully. but I got problem with when I run command main.py file. I got above problem. 

I tried with different versions also.

I don't understand that need to Know is there any dependency packages need to install
would you please help me to fix problem.

**Comment by Jongy** [comment]
Hi @sridharchary !

You can run gProfiler from source (which is what you are trying here) but it'll require to set up the environment properly with required Python dependencies and binary dependencies. It is useful when you are developing gProfiler but less convenient for a user.

Instead I suggest you try our [gProfiler binary release](https://github.com/Granulate/gprofiler/releases/tag/1.2.20), or Docker container release, as explained in the [README](https://github.com/Granulate/gprofiler#running-as-a-docker-container). It is much easier to use and requires absolutely no external dependencies.

**Comment by Jongy** [comment]
@sridharchary , I am closing this issue as I beleive it is no longer relevant. If the problem persists, you may reopen the issue and provide additional details.

(By the way, for the record, I think the problem might have been that you installed `configargparse` as user, and gProfiler is run as root, so it only looked in system paths; make sure to isntall dependencies as root)
