### ISSUE TITLE
cannot access container. when run a container Status is Restarting 

### ISSUE THREAD

**Issue by sridharchary** [Granulate/gprofiler#360]
When trying to access docker image of container. it's show like 
**Running Command**:
docker exec -it 720152f2c447 /bin/bash

**Response**:
Error response from daemon: Container 720152f2c447290596d2b8bc94775df1d9c863df141b48b420f9e6979f898cf6 is restarting, wait until the container is running. still it's not running.

I getting this error using docker in windows os.  can any one help me to fix errors.

**Comment by Jongy** [comment]
Hi @sridharchary !

It is possible that gProfiler is failing to start, and the container was run with `--restart=always`, hence it keeps restarting.

Can you please run `docker logs --tail 1000 720152f2c447` and post the output here? This will help understanding why the container restarts.

**Comment by Jongy** [comment]
If you are using WSL 2, [this](https://github.com/Granulate/gprofiler/issues/143#issuecomment-889875284) might be related.

**Comment by sridharchary** [comment]
@Jongy thanks for response.
I am not using WSL 2. executing from power shell using docker command.
the out of logs are look like below image.

![docker_logs_capture](https://user-images.githubusercontent.com/25578991/167540508-9465acc3-d73a-4244-9e3e-2a2a04d312d7.PNG)

**Comment by sridharchary** [comment]
> If you are using WSL 2, [this](https://github.com/Granulate/gprofiler/issues/143#issuecomment-889875284) might be related.

it's worked --disable-pids-check.

but not sync with [gprofiler ](https://profiler.granulate.io/)  site.

**Comment by Jongy** [comment]
I see. When you use `docker run` in Windows, the Docker container actually runs on the WSL (or WSL2) that runs on your system.

This solves the issue. I will add a word on it in the documentation. Will update here once that's done.

I see that you've opened https://github.com/Granulate/gprofiler/issues/364 to discuss the data issue, I am closing this issue which was about starting the profiler, and we'll continue discussing there.
