### ISSUE TITLE
while running Gprofiler

### ISSUE THREAD

**Issue by sridharchary** [Granulate/gprofiler#401]
I modified Dockerfile below line
ENTRYPOINT [ "python3", "-m", "gprofiler", "--disable-pidns-check","--no-java"]
![gprofiler_api_call_error](https://user-images.githubusercontent.com/25578991/177727725-b92ea3a8-1130-4854-bc9d-31113e2d753a.PNG)

the file in gprofiler\client.py of APIClient class, but how can I resolve issue.

**Comment by Jongy** [comment]
Hi @sridharchary , can you please try the latest version (1.2.27), and if the issue persists, run gProfiler with `--curlify-requests` which will log the sent requests, then post one request here and this will help me debug it on the backend :)

**Comment by Jongy** [comment]
Closing this as it's old, feel free to reopen if the problem returns.
