### ISSUE TITLE
Failed send logs to server

### ISSUE THREAD

**Issue by gavin-jeong** [Granulate/gprofiler#405]
First time to use this, it fails to send data to server.
```
[09:19:19] Failed sending logs to server
Traceback (most recent call last):
  File "/app/gprofiler/log.py", line 167, in try_send_log_to_server
    self._api_client.post(self._path, data=self._logs[:logs_count], api_version="v1")
  File "/app/gprofiler/client.py", line 137, in post
    return self._send_request("POST", path, data, **kwargs)
  File "/app/gprofiler/client.py", line 130, in _send_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://profiler.granulate.io/api/v1/logs?key=****&service=****&hostname=****&timestamp=2022-07-14T09%3A19%3A19
```

**Comment by Jongy** [comment]
Hi @gavin-jeong , this error refers to the debug logs (not the profiling data itself - your data should be visible in the Performance Studio despite this message).
We had several issues with the logging endpoint the past week, and profilers failed to send their logs, that's probably what you're seeing here. I'm sorry for the confusion. In any case, it is resolved now.

**Comment by Jongy** [comment]
I'm closing as the logging endpoint is functioning okay and no further details are given here. If the problem returns and/or more details on the problem can be given, you may re-open the issue and continue the discussion.
