### ISSUE TITLE
k8s Daemonset pods stuck in "CrashLoopBackOff"

### ISSUE THREAD

**Issue by brijean** [Granulate/gprofiler#417]
just installed gprofiler daemonset on eks k8s cluster.  Pods keep restarting:

[cloudshell-user@ip-10-0-20-221 ~]$ kubectl get pods | grep granulate
granulate-gprofiler-t7dwh                0/1     CrashLoopBackOff   19 (75s ago)   74m
granulate-gprofiler-t855m                0/1     CrashLoopBackOff   19 (96s ago)   74m
granulate-gprofiler-w4x96                0/1     CrashLoopBackOff   19 (82s ago)   74m
granulate-maestro-6df6db74c9-t26bj       2/2     Running            0              73m

[cloudshell-user@ip-10-0-20-221 ~]$ kubectl describe pods granulate-gprofiler-t7dwh
Name:         granulate-gprofiler-t7dwh
Namespace:    default
Priority:     0
Node:         ip-192-168-17-133.us-east-2.compute.internal/192.168.17.133
Start Time:   Wed, 20 Jul 2022 19:02:24 +0000
Labels:       app=granulate-gprofiler
              controller-revision-hash=57dbd966bd
              pod-template-generation=1
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           192.168.34.230
IPs:
  IP:           192.168.34.230
Controlled By:  DaemonSet/granulate-gprofiler
Containers:
  granulate-gprofiler:
    Container ID:  docker://90d9dcab2ac6423596e6553fb12b9c651f72e65e5c7bf31bc2b8ef39dbc30d1d
    Image:         index.docker.io/granulate/gprofiler:latest
    Image ID:      docker-pullable://granulate/gprofiler@sha256:ab80eda157f96962e0dcbfd4e6f878a185802f5346b5c93c447f085de59203b8
    Port:          <none>
    Host Port:     <none>
    Args:
      -cu
      --token
      $(GPROFILER_TOKEN)
      --service-name
      $(GPROFILER_SERVICE)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 20 Jul 2022 20:45:46 +0000
      Finished:     Wed, 20 Jul 2022 20:45:47 +0000
    Ready:          False
    Restart Count:  25
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GPROFILER_TOKEN:    -2VzyckD4HHifIF8fuvspXEgHgJ5WRhfdlqVNzzZWDw
      GPROFILER_SERVICE:  EKS_Demo
      GPROFILER_IN_K8S:   1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fpz88 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-fpz88:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  113s (x492 over 106m)  kubelet  Back-off restarting failed container
[cloudshell-user@ip-10-0-20-221 ~]$

**Comment by Jongy** [comment]
Hi @brijean , thanks for the report. Can you please provide us with the output logs of one of the Pods? For example, `kubectl logs granulate-gprofiler-t7dwh --previous`. These will most likely shed light on the problem.

**Comment by brijean** [comment]
Hi, when I try to get the logs from the gprofiler container I get a Python error:

[cloudshell-user@ip-10-0-39-86 ~]$ kubectl logs granulate-gprofiler-t7dwh --previous
usage: __main__.py [-h] [--pid-file PID_FILE] [--config CONFIG] [-f FREQUENCY]
                   [-d DURATION] [-o OUTPUT_DIR] [--flamegraph]
                   [--no-flamegraph] [--rotating-output]
                   [--java-mode {ap,disabled,none}] [--no-java]
                   [--java-async-profiler-buildids] [--java-no-version-check]
                   [--java-async-profiler-mode {cpu,itimer,auto}]
                   [--java-async-profiler-safemode [0-127]]
                   [--java-async-profiler-args JAVA_ASYNC_PROFILER_ARGS]
                   [--java-safemode [JAVA_SAFEMODE]]
                   [--java-jattach-timeout JAVA_JATTACH_TIMEOUT]
                   [--java-async-profiler-mcache [0-255]]
                   [--perf-mode {fp,dwarf,smart,disabled,none}] [--no-perf]
                   [--perf-dwarf-stack-size PERF_DWARF_STACK_SIZE]
                   [--php-mode {phpspy,disabled,none}] [--no-php]
                   [--php-proc-filter PHP_PROCESS_FILTER]
                   [--python-mode {auto,pyperf,pyspy,py-spy,disabled,none}]
                   [--no-python] [--no-python-versions]
                   [--pyperf-user-stacks-pages PYTHON_PYPERF_USER_STACKS_PAGES]
                   [--ruby-mode {rbspy,disabled,none}] [--no-ruby]
                   [--nodejs-mode {perf,disabled,none}] [--no-nodejs]
                   [--log-usage] [-u] [--server-host SERVER_HOST]
                   [--server-upload-timeout SERVER_UPLOAD_TIMEOUT]
                   [--token SERVER_TOKEN] [--service-name SERVICE_NAME]
                   [--curlify-requests] [--version] [-v] [--log-file LOG_FILE]
                   [--log-rotate-max-size LOG_ROTATE_MAX_SIZE]
                   [--log-rotate-backup-count LOG_ROTATE_BACKUP_COUNT]
                   [--dont-send-logs] [--disable-container-names]
                   [--continuous] [--profile-api-version {v1}]
                   [--disable-pidns-check] [--disable-metrics-collection]
                   [--disable-metadata-collection]
                   [--disable-application-identification]
                   [--app-id-args-filter APP_ID_ARGS_FILTERS]
                   [--disable-application-metadata]
                   [--controller-pid CONTROLLER_PID]
                   [--databricks-job-name-as-service-name]
                   [--profile-spawned-processes]
__main__.py: error: argument --token: expected one argument
[cloudshell-user@ip-10-0-39-86 ~]$ 

However, I can pull logs from other pods including the granulate-maestro pod:

[cloudshell-user@ip-10-0-39-86 ~]$ kubectl logs granulate-maestro-6df6db74c9-t26bj -c granulate-maestro  --tail 10
2022-07-22 13:28:34,315 - INFO - maestro.periodic_service - Starting a new cycle {"service": "ConfiguratorService"}
2022-07-22 13:28:34,370 - INFO - maestro.periodic_service - Cycle finished {"service": "ConfiguratorService", "elapsed_seconds": 0.05388283729553223, "sleep_duration": 59.94611716270447, "success": true}
2022-07-22 13:28:57,606 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}
2022-07-22 13:28:57,618 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}
2022-07-22 13:29:27,809 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}
2022-07-22 13:29:27,812 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}
2022-07-22 13:29:34,319 - INFO - maestro.periodic_service - Starting a new cycle {"service": "ConfiguratorService"}
2022-07-22 13:29:34,382 - INFO - maestro.periodic_service - Cycle finished {"service": "ConfiguratorService", "elapsed_seconds": 0.06274199485778809, "sleep_duration": 59.93725800514221, "success": true}
2022-07-22 13:29:57,994 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}
2022-07-22 13:29:57,997 - ERROR - maestro.collection.collectors.metrics_collector - Error occurred in the metrics API, skipping its result {"error": "ApiException()"}

**Comment by Jongy** [comment]
The Python error is from the Pod itself, not from kubectl :) The issue is `main.py: error: argument --token: expected one argument`.
This is how it looks in the DaemonSet:
https://github.com/Granulate/gprofiler/blob/7bacaf9c49bae84cb361aae7e3004d50b4c3db25/deploy/k8s/gprofiler.yaml#L40-L45
Is it possible you've amended it and removed usage of `GPROFILER_TOKEN`? Or shuffled the arguments such that the token doesn't follow? That could be the cause for this error.

Otherwise - please provide the outputs of `kubectl describe ds granulate-gprofiler` (you can redact the token & service name variables)

**Comment by brijean** [comment]
Hi,

Here's the relevant section of my gprofilerDaemonset.yaml.  The service name and key seem to match what I see in the gprofiler portal.

    spec:
      containers:
      - args:
        - -cu
        - --token
        - $(GPROFILER_TOKEN)
        - --service-name
        - $(GPROFILER_SERVICE)
        env:
        - name: GPROFILER_TOKEN
          value: <omitted>
        - name: GPROFILER_SERVICE
          value:<omitted>
        - name: GPROFILER_IN_K8S
          value: '1'


Here is the output for describing the daemonset:

[cloudshell-user@ip-10-0-18-168 ~]$ kubectl describe daemonset
Name:           granulate-gprofiler
Selector:       app=granulate-gprofiler
Node-Selector:  <none>
Labels:         app=granulate-gprofiler
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=granulate-gprofiler
  Containers:
   granulate-gprofiler:
    Image:      index.docker.io/granulate/gprofiler:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      -cu
      --token
      $(GPROFILER_TOKEN)
      --service-name
      $(GPROFILER_SERVICE)
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GPROFILER_TOKEN:    <omitted>
      GPROFILER_SERVICE:  <omitted>
      GPROFILER_IN_K8S:   1
    Mounts:               <none>
  Volumes:                <none>
Events:                   <none>


Thanks
Brian

**Comment by brijean** [comment]
Hi Jongy,

I deleted the daemonset and reapplied per the instructions in the portal.   I now see the Environment variables set in the "Environment" section of "kubectl describe deployments".  I've kept the service name but omitted the token in the output below:

[cloudshell-user@ip-10-0-45-174 ~]$ kubectl describe daemonset
Name:           granulate-gprofiler
Selector:       app=granulate-gprofiler
Node-Selector:  <none>
Labels:         app=granulate-gprofiler
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=granulate-gprofiler
  Containers:
   granulate-gprofiler:
    Image:      index.docker.io/granulate/gprofiler:latest
    Port:       <none>
    Host Port:  <none>
    Args:
      -cu
      --token
      $(GPROFILER_TOKEN)
      --service-name
      $(GPROFILER_SERVICE)
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GPROFILER_TOKEN:    <omitted>
      GPROFILER_SERVICE:  EKS_Demo
      GPROFILER_IN_K8S:   1
    Mounts:               <none>
  Volumes:                <none>
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  118s  daemonset-controller  Created pod: granulate-gprofiler-qqrd4
  Normal  SuccessfulCreate  118s  daemonset-controller  Created pod: granulate-gprofiler-t579c
  Normal  SuccessfulCreate  118s  daemonset-controller  Created pod: granulate-gprofiler-2n45f


unfortunatley the pods are still stuck in crashloopbackoff

[cloudshell-user@ip-10-0-45-174 ~]$ kubectl get pods | grep granulate
granulate-gprofiler-2n45f                0/1     CrashLoopBackOff   6 (32s ago)     6m33s
granulate-gprofiler-qqrd4                0/1     CrashLoopBackOff   6 (52s ago)     6m33s
granulate-gprofiler-t579c                0/1     CrashLoopBackOff   6 (39s ago)     6m33s
granulate-maestro-6df6db74c9-86fwp       2/2     Running            0               3d23h

**Comment by Jongy** [comment]
Hi Brian, can you please provide the logs from one of the pods again? As suggested [here](https://github.com/Granulate/gprofiler/issues/417#issuecomment-1192014137). I'm thinking it could be some other problem now.

**Comment by brijean** [comment]
Hi Jongy,

logs are below:

[cloudshell-user@ip-10-0-41-112 ~]$ kubectl get pods -o wide | grep granulate
granulate-gprofiler-2n45f                0/1     CrashLoopBackOff   587 (4m7s ago)    2d1h    192.168.52.192    ip-192-168-12-101.us-east-2.compute.internal   <none>           <none>
granulate-gprofiler-qqrd4                0/1     CrashLoopBackOff   588 (58s ago)     2d1h    192.168.90.112    ip-192-168-116-13.us-east-2.compute.internal   <none>           <none>
granulate-gprofiler-t579c                0/1     CrashLoopBackOff   587 (2m26s ago)   2d1h    192.168.59.200    ip-192-168-17-133.us-east-2.compute.internal   <none>           <none>
granulate-maestro-6df6db74c9-86fwp       2/2     Running            2 (21h ago)       6d1h    192.168.55.37     ip-192-168-17-133.us-east-2.compute.internal   <none>           <none>
[cloudshell-user@ip-10-0-41-112 ~]$ kubectl logs granulate-gprofiler-2n45f --previous
usage: __main__.py [-h] [--pid-file PID_FILE] [--config CONFIG] [-f FREQUENCY]
                   [-d DURATION] [-o OUTPUT_DIR] [--flamegraph]
                   [--no-flamegraph] [--rotating-output]
                   [--java-mode {ap,disabled,none}] [--no-java]
                   [--java-async-profiler-buildids] [--java-no-version-check]
                   [--java-async-profiler-mode {cpu,itimer,auto}]
                   [--java-async-profiler-safemode [0-127]]
                   [--java-async-profiler-args JAVA_ASYNC_PROFILER_ARGS]
                   [--java-safemode [JAVA_SAFEMODE]]
                   [--java-jattach-timeout JAVA_JATTACH_TIMEOUT]
                   [--java-async-profiler-mcache [0-255]]
                   [--perf-mode {fp,dwarf,smart,disabled,none}] [--no-perf]
                   [--perf-dwarf-stack-size PERF_DWARF_STACK_SIZE]
                   [--php-mode {phpspy,disabled,none}] [--no-php]
                   [--php-proc-filter PHP_PROCESS_FILTER]
                   [--python-mode {auto,pyperf,pyspy,py-spy,disabled,none}]
                   [--no-python] [--no-python-versions]
                   [--pyperf-user-stacks-pages PYTHON_PYPERF_USER_STACKS_PAGES]
                   [--ruby-mode {rbspy,disabled,none}] [--no-ruby]
                   [--nodejs-mode {perf,disabled,none}] [--no-nodejs]
                   [--log-usage] [-u] [--server-host SERVER_HOST]
                   [--server-upload-timeout SERVER_UPLOAD_TIMEOUT]
                   [--token SERVER_TOKEN] [--service-name SERVICE_NAME]
                   [--curlify-requests] [--version] [-v] [--log-file LOG_FILE]
                   [--log-rotate-max-size LOG_ROTATE_MAX_SIZE]
                   [--log-rotate-backup-count LOG_ROTATE_BACKUP_COUNT]
                   [--dont-send-logs] [--disable-container-names]
                   [--continuous] [--profile-api-version {v1}]
                   [--disable-pidns-check] [--disable-metrics-collection]
                   [--disable-metadata-collection]
                   [--disable-application-identification]
                   [--app-id-args-filter APP_ID_ARGS_FILTERS]
                   [--disable-application-metadata]
                   [--controller-pid CONTROLLER_PID]
                   [--databricks-job-name-as-service-name]
                   [--profile-spawned-processes]
__main__.py: error: argument --token: expected one argument
[cloudshell-user@ip-10-0-41-112 ~]$

**Comment by Jongy** [comment]
Hmm, this again looks like the `GPROFILER_TOKEN` is somehow omitted. I'm not sure how it can happen if indeed the variable isn't empty.

To continue debugging it - may I suggest that you change the `args` array this way, from:
```
  - args:
    - -cu
    - --token
    - $(GPROFILER_TOKEN)
    - --service-name
    - $(GPROFILER_SERVICE)
```
to
```
  - args:
    - -cu
    - --token
    - TOKEN HERE
    - --service-name
    - $(GPROFILER_SERVICE)
```

and replace `TOKEN HERE` with your token, hard-coded?

**Comment by brijean** [comment]
Hi Jongy,

I edited the DaemonSet deployment file as follows:

    spec:
      containers:
      - args:
        - -cu
        - --token
        - -<ommitted>
        - --service-name
        - $(GPROFILER_SERVICE)

The pods are still crashing:
[cloudshell-user@ip-10-0-42-225 ~]$ kubectl get pods | grep granulate
granulate-gprofiler-6tsqm                0/1     CrashLoopBackOff   5 (19s ago)    3m32s
granulate-gprofiler-tmg9h                0/1     CrashLoopBackOff   5 (29s ago)    3m32s
granulate-gprofiler-zh2fv                0/1     CrashLoopBackOff   5 (40s ago)    3m32s
granulate-maestro-6df6db74c9-hlhvm       2/2     Running            0              3m29s

Same Token error on logs command:
[cloudshell-user@ip-10-0-42-225 ~]$ kubectl logs granulate-gprofiler-6tsqm --previous
usage: __main__.py [-h] [--pid-file PID_FILE] [--config CONFIG] [-f FREQUENCY]
                   [-d DURATION] [-o OUTPUT_DIR] [--flamegraph]
                   [--no-flamegraph] [--rotating-output]
                   [--java-mode {ap,disabled,none}] [--no-java]
                   [--java-async-profiler-buildids] [--java-no-version-check]
                   [--java-async-profiler-mode {cpu,itimer,auto}]
                   [--java-async-profiler-safemode [0-127]]
                   [--java-async-profiler-args JAVA_ASYNC_PROFILER_ARGS]
                   [--java-safemode [JAVA_SAFEMODE]]
                   [--java-jattach-timeout JAVA_JATTACH_TIMEOUT]
                   [--java-async-profiler-mcache [0-255]]
                   [--perf-mode {fp,dwarf,smart,disabled,none}] [--no-perf]
                   [--perf-dwarf-stack-size PERF_DWARF_STACK_SIZE]
                   [--php-mode {phpspy,disabled,none}] [--no-php]
                   [--php-proc-filter PHP_PROCESS_FILTER]
                   [--python-mode {auto,pyperf,pyspy,py-spy,disabled,none}]
                   [--no-python] [--no-python-versions]
                   [--pyperf-user-stacks-pages PYTHON_PYPERF_USER_STACKS_PAGES]
                   [--ruby-mode {rbspy,disabled,none}] [--no-ruby]
                   [--nodejs-mode {perf,disabled,none}] [--no-nodejs]
                   [--log-usage] [-u] [--server-host SERVER_HOST]
                   [--server-upload-timeout SERVER_UPLOAD_TIMEOUT]
                   [--token SERVER_TOKEN] [--service-name SERVICE_NAME]
                   [--curlify-requests] [--version] [-v] [--log-file LOG_FILE]
                   [--log-rotate-max-size LOG_ROTATE_MAX_SIZE]
                   [--log-rotate-backup-count LOG_ROTATE_BACKUP_COUNT]
                   [--dont-send-logs] [--disable-container-names]
                   [--continuous] [--profile-api-version {v1}]
                   [--disable-pidns-check] [--disable-metrics-collection]
                   [--disable-metadata-collection]
                   [--disable-application-identification]
                   [--app-id-args-filter APP_ID_ARGS_FILTERS]
                   [--disable-application-metadata]
                   [--controller-pid CONTROLLER_PID]
                   [--databricks-job-name-as-service-name]
                   [--profile-spawned-processes]
__main__.py: error: argument --token: expected one argument
[cloudshell-user@ip-10-0-42-225 ~]$ 

Here's the output of kubectl describe pods.  It does seem to have the correct Key applied but I have omitted it below:

[cloudshell-user@ip-10-0-42-225 ~]$ kubectl describe pods granulate-gprofiler-6tsqm
Name:         granulate-gprofiler-6tsqm
Namespace:    default
Priority:     0
Node:         ip-192-168-17-133.us-east-2.compute.internal/192.168.17.133
Start Time:   Mon, 01 Aug 2022 20:39:35 +0000
Labels:       app=granulate-gprofiler
              controller-revision-hash=789bd7c44f
              pod-template-generation=1
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           192.168.33.71
IPs:
  IP:           192.168.33.71
Controlled By:  DaemonSet/granulate-gprofiler
Containers:
  granulate-gprofiler:
    Container ID:  docker://72e1ef88ce9c54235df4d9a11951ab00aac1f1a8e0c5ddae1600ed129ed723e1
    Image:         index.docker.io/granulate/gprofiler:latest
    Image ID:      docker-pullable://granulate/gprofiler@sha256:ab80eda157f96962e0dcbfd4e6f878a185802f5346b5c93c447f085de59203b8
    Port:          <none>
    Host Port:     <none>
    Args:
      -cu
      --token
      -2VzyckD4HHifIF8fuvspXEgHgJ5WRhfdlqVNzzZWDw
      --service-name
      $(GPROFILER_SERVICE)
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 01 Aug 2022 20:42:48 +0000
      Finished:     Mon, 01 Aug 2022 20:42:48 +0000
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     500m
      memory:  1Gi
    Requests:
      cpu:     100m
      memory:  256Mi
    Environment:
      GPROFILER_TOKEN:    <omitted>
      GPROFILER_SERVICE:  EKS_Demo
      GPROFILER_IN_K8S:   1
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lbr6b (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-lbr6b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m40s                  default-scheduler  Successfully assigned default/granulate-gprofiler-6tsqm to ip-192-168-17-133.us-east-2.compute.internal
  Normal   Pulled     5m39s                  kubelet            Successfully pulled image "index.docker.io/granulate/gprofiler:latest" in 265.345447ms
  Normal   Pulled     5m38s                  kubelet            Successfully pulled image "index.docker.io/granulate/gprofiler:latest" in 232.64543ms
  Normal   Pulled     5m20s                  kubelet            Successfully pulled image "index.docker.io/granulate/gprofiler:latest" in 243.575549ms
  Normal   Created    4m50s (x4 over 5m39s)  kubelet            Created container granulate-gprofiler
  Normal   Pulled     4m50s                  kubelet            Successfully pulled image "index.docker.io/granulate/gprofiler:latest" in 227.816505ms
  Normal   Started    4m49s (x4 over 5m39s)  kubelet            Started container granulate-gprofiler
  Normal   Pulling    3m59s (x5 over 5m40s)  kubelet            Pulling image "index.docker.io/granulate/gprofiler:latest"
  Warning  BackOff    26s (x25 over 5m36s)   kubelet            Back-off restarting failed container
[cloudshell-user@ip-10-0-42-225 ~]$

**Comment by Jongy** [comment]
Okay, I understand the problem. Your token begins with `-` and argparse takes it as a separate argument. I fixed the instructions [here](https://github.com/Granulate/gprofiler/pull/325) to avoid it, but forgot to update the k8s/ecs as well :/ Will do so now.

To fix your case - 
```
spec:
  containers:
  - args:
    - -cu
    - --token=$(GPROFILER_TOKEN)
    - --service-name=$(GPROFILER_SERVICE)
```

**Comment by brijean** [comment]
Hi Jongy,

using the "=" format did the trick.  

Thanks for your help.

Brian

**Comment by Jongy** [comment]
I'm glad to hear that!
