### ISSUE TITLE
Unable to download ECS task definition JSON

### ISSUE THREAD

**Issue by contentfree** [Granulate/gprofiler#419]
When clicking on the link this is shown in the browser console: 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/10958/180324465-9a8248a3-f7fe-4d2f-92c4-9938e4f54707.png">

Chrome 103.0.5060.114 on macOS Monterey

The received response is `"Failed to get ECS template"`

**Comment by Jongy** [comment]
Hi @contentfree ! Thanks for reporting this, we will look into it and update back here :)

Meanwhile you can get the ECS task definition from this GitHub repo - check out the ECS instructions in the README.

**Comment by Jongy** [comment]
Hi @contentfree , the issue is resolved now.
