### ISSUE TITLE
got issue when ran gprofiler in local and kubernets server cluster

### ISSUE THREAD

**Issue by sridharchary** [Granulate/gprofiler#427]
can anyone help me to how to fix this issue

from granulate_utils.linux.elf import get_mapped_dso_elf_id
ImportError: cannot import name 'get_mapped_dso_elf_id' from 'granulate_utils.linux.elf' (/home/ubuntu/Desktop/gprofiler/granulate_utils/linux/elf.py)

from granulate_utils.linux.elf import read_process_execfn
ImportError: cannot import name 'read_process_execfn' from 'granulate_utils.linux.elf' (/home/ubuntu/.local/lib/python3.8/site-packages/granulate_utils/linux/elf.py)

**Comment by Jongy** [comment]
Hi @sridharchary , it looks like gProfiler & its dependencies were not properly installed. Please make sure the granulate-utils submodule is up to date by running `git submodule update` and re-running the installation (`cd granulate-utils && pip install .`, in the Python context where you're going to run gProfiler).

Alternatively - you can use the image installation / executable installation, then you don't need to mess around with dependencies :)

**Comment by Jongy** [comment]
I'm closing this ticket as my previous comment explains the needed fix (to update submodules). If the problem persists, feel free to reopen this ticket.
