### ISSUE TITLE
what is .col function in gprofiler and can I convert this file into any other format

### ISSUE THREAD

**Issue by sridharchary** [Granulate/gprofiler#548]
I browsing on internet searched about .col file there is no such results to related to this file.
attached to .txt format.
[last_profile.txt](https://github.com/Granulate/gprofiler/files/9838206/last_profile.txt)

**Comment by Jongy** [comment]
I will create a PR that adds documentation for the file format :)

**Comment by Jongy** [comment]
@sridharchary , you can read the documentation I added in https://github.com/Granulate/gprofiler/pull/549 until it gets merged.
