### ISSUE TITLE
pyperf: Upgrade bcc

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#616]
As suggested in https://github.com/Granulate/gprofiler/pull/579#issuecomment-1331134830, we haven't upgraded bcc in a while (or rather, never since we incorporated it). It's a live project that probably received bugifxes and performance improvements. We have proper tests in place for pyperf, so we should give it a try.

**Comment by marcin-ol** [comment]
One of good reasons for upgrading bcc - a commit in the upstream bcc: 
[bcc/syms: Fix shared lib module offset <-> global addr conversion](https://github.com/iovisor/bcc/commit/4b3cbf44ba9eb9d5a7d11c69a7238497889ce2fc)
