### ISSUE TITLE
java: async-profiler: test that no output is written to process stdout/stderr

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#649]
async-profiler writes in the process' stdout/stderr. We have removed those prints - see https://github.com/Granulate/async-profiler/commit/35531a45a197048a450aca38386d144dfa1060bb and https://github.com/Granulate/async-profiler/commit/473b925f4a82bd7bd53b0737e3ead238c38f7a09.

We should have a test that proves that no additional output is written to stdout/stderr during the cycle of a single profiling session, i.e start/stop of AP. stdout & stderr should remain empty, or, should contain the only output that the profiled app is printing. I suggest adding a `System.out.println(...)` and `System.err.println(...)` to our Fibonacci Java app and then compare the output of the process to those 2 prints.

**Comment by Jongy** [comment]
(I want it tested continuously because as we upgrade AP, we might accidentally introduce prints that are added in new versions)

**Comment by marcin-ol** [comment]
Do you mean we want to make sure no code writes explicitly to stdout?

I'm asking because the commits you have mentioned didn't write directly to stdout.
We directed output to a stream **out**, which is an instance of `ofstream` initialized with argument `file=` passed to jattach.
And we always set the `file=` argument.

**Comment by marcin-ol** [comment]
Found out that the test needed only call `flush()` on output stream to reproduce the behavior.

**Comment by Jongy** [comment]
If I run async-profiler from master on a Java process, I get `Profiling started` prints in the stdout of the Java process itself. That's what we are trying to avoid in removing those logs.
