### ISSUE TITLE
perf: Upgrade to Linux v6.4

### ISSUE THREAD

**Issue by Jongy** [Granulate/gprofiler#820]
I have an [existing PR to upgrade for v6.3](https://github.com/Granulate/gprofiler/pull/752). Since then, v6.4 was released, so we can use it.
Use branch https://github.com/Granulate/linux/tree/granulate-perf-v6.3 and merge the latest kernel release into it, then test gProfiler with it.

**Comment by roi-granulate** [comment]
perf was upgraded to v6.7 in #888
